TARGET		= nanotodon
OBJS_TARGET	= nanotodon.o sbuf.o squeue.o utils.o config.o messages.o

CFLAGS = -g
# optimization
#CFLAGS+= -O2
# Use $XDG_CONFIG_HOME or ~/.config dir to save config files
CFLAGS+= -DSUPPORT_XDG_BASE_DIR -D_XOPEN_SOURCE -D_DEFAULT_SOURCE -D_BSD_SOURCE -DNCURSES_WIDECHAR

LIBS = -lcurl -lpthread -lm

include Makefile.in
